# Generated by Django 3.2.25 on 2025-01-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
