# Generated by Django 3.2.25 on 2025-01-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='repayment_duration',
            field=models.CharField(choices=[('1week', '1 week - 15% interest'), ('2weeks', '2 weeks - 20% interest'), ('3weeks', '3 weeks - 30% interest'), ('4weeks', '4 weeks - 40% interest')], default='1week', max_length=7),
        ),
    ]
