# Generated by Django 3.2.25 on 2025-01-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20250122_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='bank_statement',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='nrc_back',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='nrc_front',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='pay_slip',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='photo',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='Collateral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
