# Generated by Django 3.2.25 on 2025-01-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20250125_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='Collateral',
            new_name='collateral',
        ),
    ]
