# Generated by Django 3.2.25 on 2025-06-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_collateral_loanapplication_collateral'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='nrc_number',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
