# Generated by Django 3.2.25 on 2025-06-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_loanapplication_nrc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='phone_number',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
