# Generated by Django 3.2.25 on 2025-07-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_loanapplication_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='nrc_photo',
            field=models.ImageField(blank=True, null=True, upload_to='nrc_photos/'),
        ),
    ]
