# Generated by Django 3.2.25 on 2025-07-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_loanapplication_nrc_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='estimated_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
